/* 🤖 this file was generated by svg-to-ts */
const SvgSpinner = (props: { [key: string]: any }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="200"
        height="200"
        fill="none"
        stroke="currentColor"
        strokeWidth="0"
        viewBox="0 0 24 24"
        {...props}
    >
        <path
            fill="currentColor"
            fillRule="evenodd"
            stroke="none"
            d="M12 19a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm0 3c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Z"
            clipRule="evenodd"
            opacity=".2"
        />
        <path
            fill="currentColor"
            stroke="none"
            d="M2 12C2 6.477 6.477 2 12 2v3a7 7 0 0 0-7 7z"
        />
    </svg>
);

export default SvgSpinner;
