export const ERROR_SOMETHING_BAD_HAPPENED = 'ERROR_SOMETHING_BAD_HAPPENED';
export const REQUEST_HEADER_AUTH_KEY = 'REQUEST_HEADER_AUTH_KEY';
export const SERVER_ERROR = 'SERVER_ERROR';
export const TOKEN_TYPE = 'TOKEN_TYPE';
export const WARNING_YOUR_SESSION_HAS_EXPIRED = 'WARNING_YOUR_SESSION_HAS_EXPIRED';